config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'
  resources :articles do
    resources :comments, only: %i[create destroy]
  end
  resources :categories
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
# frozen_string_literal: true

class Article < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :article_categories, dependent: :destroy
  has_many :categories, through: :article_categories

  validates :title, presence: true
  validates :body, presence: true, length: { in: 5..300 }
end

app/models/article_category.rb
# frozen_string_literal: true

class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :article_categories, dependent: :destroy
  has_many :articles, through: :article_categories

  validates :name, presence: true, uniqueness: { case_sensitive: false }
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :article

  validates :message, presence: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# Controls the application
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

# Controls articles
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[show edit update destroy]

  # GET /articles or /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1 or /articles/1.json
  def show; end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit; end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_article
    @article = Article.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def article_params
    params.require(:article).permit(:title, :body, category_ids: [])
  end
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

# Helper for Categories
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show; end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit; end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

# Controls for comments
class CommentsController < ApplicationController
  before_action :set_article

  def create
    if @article.comments.create(comment_params).valid?
      redirect_to @article, notice: 'Comment was successfully posted.'
    else
      redirect_to @article, alert: 'Comment invalid.'
    end
  end

  def destroy
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to @article, notice: 'Comment was successfully destroyed.'
  end

  private

  def set_article
    @article = Article.find(params[:article_id])
  end

  def comment_params
    params.require(:comment).permit(:message)
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

# Controls home
class HomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# Helper for views
module ApplicationHelper
  def active?(current)
    request.path == current ? ' active' : nil
  end

  def form_errors(object)
    render 'shared/form_errors', object:
  end
end

app/helpers/articles_helper.rb
# frozen_string_literal: true

# Helper for articles
module ArticlesHelper
end

app/helpers/categories_helper.rb
# frozen_string_literal: true

# Helper for Categories
module CategoriesHelper
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

# Helper for comments
module CommentsHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

# Helper for home
module HomeHelper
end

app/views/articles/_article.html.erb
<div id="<%= dom_id article %>" class="card col-md-8 shadow mb-4 mx-auto">
  <div class="card-header">
    <div>Username</div>
    <%= render 'categories/badge', categories: article.categories %>
  </div>

  <div class="card-body">
    <h5 class="card-title">
      <%= article.title %>
    </h5>

    <p class="card-text">
      <%= article.body %>
    </p>

    <div>
      <%= link_to 'Show', article, class:'btn btn-primary btn-sm' if request.path != article_path(article) %>
      <%= link_to 'Edit', [:edit, article], class:'btn btn-secondary btn-sm' %>
      <%= button_to 'Delete', article, method: :delete, confirm: 'Are you sure?', class: 'btn btn-danger btn-sm', form: { class: 'd-inline' } %>
    </div>
  </div>
  <div class="card-footer text-muted">
    <small>Created <%= time_ago_in_words(article.created_at) %> ago, updated <%= time_ago_in_words(article.updated_at) %> ago.</small>
  </div>

</div>

app/views/articles/_form.html.erb
<%= form_with(model: article, html: { class:'text-start' }) do |form| %>
  <%= form_errors(article) %>

  <div class="mb-2">
    <%= form.label :title, class:'form-label' %>
    <%= form.text_field :title, class:'form-control' %>
  </div>

  <div class="mb-2">
    <%= form.label :body, class:'form-label' %>
    <%= form.text_area :body, class:'form-control' %>
  </div>

  <div class="mb-2">
    <%= form.collection_select :category_ids, Category.order(:name), :id, :name, { prompt: true }, { size: 3, class: 'form-select', multiple: true } %>
  </div>

  <div class="mb-2">
    <%= form.submit class:'btn btn-primary' %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to 'Back to article', article_path(@article), class:'btn btn-secondary btn-sm' %>
</div>

app/views/articles/index.html.erb
<h1>Articles</h1>

<div id="articles">
  <% @articles.each do |article| %>
    <%= render article %>
  <% end %>
</div>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to 'Back to articles', articles_path, class:'btn btn-secondary btn-sm' %>
</div>

app/views/articles/show.html.erb
<%= render @article %>

<h5>Comments:</h5>

<%= render @article.comments %>

<%= render 'comments/form' %>

<div>
  <%= link_to 'Back to articles', articles_path, class:'btn btn-secondary btn-sm' %>
</div>

app/views/categories/_badge.html.erb
<div>
  <% categories.each do |cat| %>
    <span class="badge rounded-pill bg-info"><%= link_to cat.name, cat, class: 'text-decoration-none text-dark' %></span>
  <% end %>
</div>

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>" class="card shadow mb-4 mx-auto col-10 col-sm-6">
  <h5 class="card-header"><%= category.name %></h5>
  <div class="card-body">
    <p class="card-text"><%= pluralize(category.articles.count, "article") %></p>
    <%= link_to 'Show', category, class: 'btn btn-primary btn-sm' %>
    <%= link_to 'Edit', [:edit, category], class: 'btn btn-secondary btn-sm' %>
    <%= button_to 'Delete', category, method: :delete, confirm: 'Are you sure?', class: 'btn btn-danger btn-sm', form: { class: 'd-inline' } %>
  </div>

</div>

app/views/categories/_form.html.erb
<%= form_with(model: category, html: { class: 'text-start' }) do |form| %>
  <%= form_errors(category) %>

  <div class="mb-2">
    <%= form.label :name, class: 'form-label' %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="mb-2">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back to categories", @category, class: 'btn btn-secondary btn-sm' %>
</div>

app/views/categories/index.html.erb
<h1>Categories</h1>

<div id="categories">
  <% @categories.each do |category| %>
    <%= render category %>
  <% end %>
</div>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back to categories", categories_path, class: 'btn btn-secondary btn-sm' %>
</div>

app/views/categories/show.html.erb
<%= render @category %>

<%= render @category.articles %>

<div>
<%= link_to "Back to categories", categories_path, class: 'btn btn-secondary btn-sm' %>
</div>

app/views/comments/_comment.html.erb
<div id="<%= dom_id(comment, dom_id(comment.article)) %>" class="card col-sm-6 col-9 shadow mb-4 mx-auto">
  <div class="card-header">
    Username
  </div>

  <div class="card-body">
    <p class="card-text">
      <%= comment.message %>
    </p>

    <div>
      <%= button_to 'Delete', [comment.article, comment], method: :delete, class:'btn btn-danger btn-sm' %>
    </div>
  </div>
  <div class="card-footer text-muted">
    <small>Created <%= time_ago_in_words(comment.created_at) %> ago.</small>
  </div>

</div>

app/views/comments/_form.html.erb
<%= form_with(model: [@article, @article.comments.build], html: { class: 'text-start col-md-6 shadow mb-4 mx-auto' }) do |form| %>

  <div class="input-group rounde my-4">
    <%= form.label :message, class: 'form-label visually-hidden' %>
    <%= form.text_field :message, placeholder: 'Post your comment here', class: 'form-control rounded' %>
    <%= form.submit :message, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render "form" %>

<br>

<div>
  <%= link_to 'Back to article', article_path(@article), class:'btn btn-secondary btn-sm' %>
</div>

app/views/home/index.html.erb
<div class="container border p-5 bg-secondary bg-gradient">
  <h1>Social Media App</h1>
  <hr>
  <p>Welcome to Social Media Application</p>

  <%= link_to 'Sign up Now!', '#', class: 'btn btn-primary my-3' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SocialMedia</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body style="margin-bottom: 80px;">
    <%= render 'shared/navbar' %>
    <div class="text-center container my-4">
      <%= render 'shared/flash' %>
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_flash.html.erb
<% flash.each do |type, message| %>
  <div class="alert alert-<%= type == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
    <strong><%= message %></strong>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="fixed-bottom bg-dark text-center">
  <div class="container d-flex justify-content-between text-muted py-3">
    <div>My</div>
    <div>Social</div>
    <div>Media</div>
  </div>
</footer>

app/views/shared/_form_errors.html.erb
<% if object.errors.any? %>
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <h4><%= pluralize(object.errors.count, "error") %> prohibited this <%= object.class.name.downcase %> from being saved:</h4>
    <ul class="m-0">
      <% object.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="/">Social Media</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Home', root_path, class:"nav-link#{active?(root_path)}" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle<%= active?(articles_path) %>" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Articles
          </a>
          <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDropdown">
            <li><%= link_to 'View Articles', articles_path, class:'dropdown-item' %></li>
            <li><hr class="dropdown-divider"></li>
            <li><%= link_to 'Create article', new_article_path, class:'dropdown-item' %></li>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle<%= active?(categories_path) %>" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Categories
          </a>
          <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDropdown">
            <li><%= link_to 'View Categories', categories_path, class:'dropdown-item' %></li>
            <li><hr class="dropdown-divider"></li>
            <li><%= link_to 'Create category', new_category_path, class:'dropdown-item' %></li>
          </ul>
        </li>
      </ul>
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <% if true %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle active" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Username
            </a>
            <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="#">Edit Profile</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="#">Delete Account</a></li>
            </ul>
          </li>
          <li class="nav-item my-1 m-lg-0">
            <%= link_to 'Logout', '#', class:'btn btn-danger' %>
          </li>
        <% else %>
          <li class="nav-item mb-2 mb-lg-0 me-lg-1">
            <%= link_to 'Login', '#', class:'btn btn-primary' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign up', '#', class:'btn btn-success' %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>